#
# MSIM configuration script
#

add drvcpu cpu0

add rom bootmem 0x00000000
bootmem generic 4096k
bootmem load "kernel.rom"

add rwm mainmem 0x80000000
mainmem generic 16M
#mainmem load "/dev/zero"

add dprinter printer 0x10000000
add dkeyboard keyboard 0x10000000 2
add dlcd lcd 16 4 0x10000010
